### PR TITLE
Fix error run in FreeBSD

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
security.bsd.see_other_uids=1
security.bsd.see_other_gids=1

**Comment by perusio** [comment]
Thanks.

**Comment by ghost** [comment]
https://github.com/InDOX/nginx_munin/commit/725c71ddca1848b73eec7d41e9357699afd1353a

**Comment by perusio** [comment]
[Done](https://github.com/perusio/nginx-munin/commit/fba599a6778bebd429793f99361ba6faec02ff74). Thank you.

**Pull request merged**
